name: Spring-Boot-Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  setup-java:
    runs-on: ubuntu-latest
    outputs:
      java-home: ${{ steps.setup-java.outputs.java-home }}
    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  cache-maven:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
          
  build:
    needs: [checkout, setup-java, cache-maven]
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: mvn clean install

      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: naruto22/spring-docker
          tags: latest
          registry: docker.io
          dockerfile: DockerFile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  test:
    needs: [checkout, setup-java]
    runs-on: ubuntu-latest
    steps:
      - name: Test with Maven
        run: mvn test
